### ISSUE TITLE
TableGateway LifeCycle Events support

### ISSUE THREAD

**Issue by ezkimo** [laminas/laminas-paginator-adapter-laminasdb#20]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Since laminas/laminas-db TableGateway implementations support life cycle events it would be nice if this package can support the events `preSelect` and `postSelect` when calling the `DbSelect::getItems()` method. The current situation triggers none of the select life cycle events. Added TableGateway Features or Event Listeners just don 't happen, when the select statement is executed in the adapter.

### Example
The following example shows a TableGateway factory adding a TableGateway Feature, that will not be excuted with the current state of the package.
```
<?php

declare(strict_types=1);

namespace Marcel\Db\TableGateway\Factory;

use Laminas\Db\ResultSet\HydratingResultSet;
use Laminas\Db\TableGateway\Feature\FeatureSet;
use Laminas\Hydrator\HydratorPluginManager;
use Marcel\Db\TableGateway\Feature\MySelectFeature;
use Marcel\Entity\MyEntity;
use Marcel\Hydrator\MyHydrator;
use Psr\Container\ContainerInterface;

class MyTableGatewayFactory
{
    public function __invoke(ContainerInterface $container): TableGateway
    {
        $adapter = $container->get('my_adapter');
        
        $hydrator = container->get(HydratorPluginManager::class)->get(MyHydrator::class);
        $resultset = new HydratingResultSet($hydrator, new MyEntity());

        $features = new FeatureSet();
        $features->addFeature(new MySelectFeature());

        return new TableGateway('my_table', $adapter, $features, $resultset);
    }
}
```

The feature won 't be executed because the paginator adapters lack of triggering the corresponding events for the executed pagination statement. Another, perhaps easier example is adding an event.

```
eventManager = new \Laminas\EventManager\EventManager();
$eventManager->attach('preSelect', function (\Laminas\Db\TableGateway\Feature\EventFeature\TableGatewayEvent $event) {
    // do some fancy stuff with the select object
});

$feature = new \Laminas\Db\TableGateway\Feature\EventFeature($eventManager);
$table = new \Laminas\Db\TableGateway\TableGateway("test_table", $adapter, $feature);
```

### Possible Solution

Since the `DbSelect` paginator adapter lacks of accessing the table gateway, a possible solution could be adding a `getItems` method to the `DbTableGateway` paginator adapter.

```
<?php

declare(strict_types=1);

namespace Laminas\Paginator\Adapter\LaminasDb;

use Closure;
use Laminas\Db\Sql\Having;
use Laminas\Db\Sql\Where;
use Laminas\Db\TableGateway\AbstractTableGateway;
use Laminas\Db\TableGateway\Feature\EventFeatureEventsInterface;

class DbTableGateway extends DbSelect
{
    ...

    public function getItems($offset, $itemCountPerPage)
    {
        $select = clone $this->select;
        $select->offset($offset);
        $select->limit($itemCountPerPage);

        $this->tableGateway->getFeatureSet()->apply(EventFeatureEventsInterface::EVENT_PRE_SELECT, [ $select ]);

        $statement = $this->sql->prepareStatementForSqlObject($select);
        $result    = $statement->execute();

        $resultSet = clone $this->resultSetPrototype;
        $resultSet->initialize($result);

        $this->tableGateway->getFeatureSet()->apply(EventFeatureEventsInterface::EVENT_POST_SELECT, [ $statement, $result, $resultSet ]);

        return iterator_to_array($resultSet);
    }
}
```

With this small change all added features or select* event listeners will be executed.
What do you think?

**Comment by Ocramius** [comment]
I'd probably phase out events there, and instead have your own `ResultSet` iterator work with that :thinking:

**Comment by ezkimo** [comment]
Sorry for the late reply. Customer projects, travelling, tv productions ... wish the current days had 48 hours.

Wouldn't a corresponding `FilterIterator` / `LimitIterator` implementation for the `ResultSet` mean that I basically read out all data sets first in order to then filter them? Doesn't that make a database-based paginator superfluous? Please correct me if I'm on the wrong track. 

I can't imagine that it would be fundamentally more advantageous to always read out all data records without first restricting them with a corresponding where statement. Isn't it better to restrict the select statement with an additional Where restriction? Isn't it better to get fewer results from the database?

In my current case the added WHERE statement had to be added dynamically based on user authentication and matching tenants of a authenticated user and the datasets to select. Sure, that all could have been done by a simple `SELECT * FROM foo LIMIT 10 OFFSET 1`. But if I filter the results there 'd be propably only 3 matching results out of 10 selected results. 

I'm really barking up the wrong tree, aren't I?

**Comment by Ocramius** [comment]
> I basically read out all data sets first in order to then filter them? 

Not really:

```php
$iterator = $query->gimmeResultSet();

$filtered = (function (iterable $result) {
    foreach ($result as $row) {
        if (condition($row)) {
            yield $row;
        }
    }
})($iterator);
```

The above is just an example: `$filtered` is not loaded in memory.

I perhaps misunderstood your use-case though: you want a hook into all queries before they get run, so you can modify them?

**Comment by ezkimo** [comment]
> you want a hook into all queries before they get run, so you can modify them?

Exactly! That 's what table gateway features are made for. At least that's what I thought until just now. At the moment I'm a little unsure. In my usecase everything depends on the authentication. So if a user has a specific option (in this case a specific tenant) all select statements for this table (table gateway) should be restricted by a where statement. I was curious why this package does not support table gateway features.

Events are practical here. Laminas-db table gateways support them natively through its lifecycle events. The only thing I have to do is adding a feature set in the table gateway factory. This means that all select statements are automatically narrowed down. Wherever I use this one table gateway.

Btw ... yeah! We all should use more generators. But in this one case ... it does not seem to be practicable. ;)

**Comment by froschdesign** [comment]
I understand the motivation behind this feature request because the current table gateway adapter is more a wrapper around the db select adapter and does not really use the table gateway class.

But on the other side: laminas-db is in security-only maintenance mode and marked as feature-complete, so this component should also marked as security-only and feature-complete.

**Comment by froschdesign** [comment]
[This component will be discontinued.](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2024-11-04-TSC-Minutes.md#archive--abandon-various-legacy-libraries)

This does not prevent anyone from creating their own adapters for laminas-paginator.
laminas-paginator itself is explicitly not affected by this.
